### PR TITLE
Adding option to run with containers

### PR DESCRIPTION
**Pull request by vsoch**
hey @bbodi ! This isn't working in full yet, but I wanted to show you progress for adding the Dockerfile (and running with Singularity)! When I know what needs writable, I should be able to modify this (and instructions) to be fully working. Relevant issue is in #12 

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Rebuilding the container now - without needing write the Singularity image should work! I'll update the PR with progress.

**Comment by vsoch** [comment]
hey @BalazsBodi this is ready to go! I've provided complete instructions for building the containers (the challenge is getting the assets on a linux machine) and also provided a pre-build container that can be pulled into singularity, where it can easily run without any fuss with the display. This is redundant for the docker/README.md, but basically the user can pull from Docker:

```bash
$ singularity pull docker://vanessa/rustarok
```

And then shell into the container, and issue the same cargo run command.

```bash
$ touch /tmp/.cargo-lock
$ singularity shell --bind /tmp/.cargo-lock:/code/target/debug/.cargo-lock rustarok_latest.sif
$ cd /code
$ cargo run
```
Now that you've fixed the write / read only issue, after the assets load, we can play! Here is me walking around on my Ubuntu:

ubuntu-play

This is ready for merge. Thanks for all your help in the process!

**Comment by bbodi** [comment]
That is awesome, thanks for your efforts!
I will go through the instructions myself and merge this PR if everything is ok.

Some notes:
- as I can see, it runs debug version. The 20 seconds waiting time you experience at the beginning almost completely disappears in release mode, and you get much better performance generally.
- Addition to that, in config-runtime.toml you can set ``sleep_ms = 10`` to 0. It is a configuration for intentionally reducing the FPS.

Some gameplay info if you want to have some fun:
- You can cast skills with Q,W,E,R,1,2,3 buttons
- You can change skills with F12 button.
- You can open your console with ALT-` (the button left to '1') (console commands and parameters are autocompleted)
- Currently some skills and browser client support does not work, but I will fix them in the next 1-2 days.

**Comment by vsoch** [comment]
Ah I will try release mode and rebuild the container! I can try to create a build argument to control the sleep_ms, with default being 0.

**Comment by vsoch** [comment]
It works great! The new entrypoint can be /code/target/release/rustarok directly, so I'm re-building again so that it works without a hitch for the docker base and Singularity image generated from it. Still building, will post when pushed.

**Comment by vsoch** [comment]
hey @bbodi this is again ready for review! 

 - I've added the frames per second as a build arg, and actually there isn't any reason the user couldn't modify the runtime file from the host and bind to the container at runtime (to avoid rebuild). It does run much faster!
 -  I removed the gif because it never looked as fast as it was running on my machine. and you already have gifs in the main README.
 - The change to build release (and then run `/target/release/rustarok`) works great - it removes any need to bind files to the container, and allows for a clean entrypoint that singularity can grab from the Docker container. Instead of the original shell command, we can just do:

```bash
$ singularity run --pwd /code rustarok_latest.sif
```
That's it! Please feel free to ping me if any issues arise that are related to containers.

**Comment by vsoch** [comment]
@BalazsBodi do you need anything else from me? You work very actively on this repo so it's going to get further away from master (and harder to potentially merge).

**Comment by bbodi** [comment]
@vsoch , don't worry, this week I am busy with work so I can't work on rustarok, but after that I will start testing and reviewing this PR.

**Comment by vsoch** [comment]
Great! Yeah I'm also heavily into work things, and trying to plow through so I can get to the fun stuff :)

**Comment by vsoch** [comment]
woohoo! Thanks @bbodi :)

**Pull request merged**
